name: "Check Dependabot Alerts"

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main

jobs:
  check-dependabot-alerts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install jq
      run: sudo apt-get install jq -y

    - name: Get Dependabot Alerts
      id: fetch-alerts
      run: |
        curl -H "Accept: application/vnd.github+json" \
             -H "Authorization: Bearer ${{ secrets.GI
