name: 'Dependabot Critical/High Alert Check'
on:
  push:
    branches:
      - master  # master branch'i için push olayı
  pull_request:
    branches:
      - master  # master branch'i için PR olayı

jobs:
  dependabot-critical-high-check:
    name: 'Critical/High Alert Check'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3

      - name: 'Fetch Dependabot A
