name: Block High and Critical Dependabot PRs

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  block_high_severity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check if PR is a dependabot update and has high/critical labels
        id: dependabot_check
        run: |
          if [ "${GITHUB_ACTOR}" == 'dependabot[bot]' ]; then
            for label in ${{ github.event.pull_request.labels.*.name }}; do
              if [[ "${label}" == *"critical"* || "${label}" == *"high"* ]]; then
                echo "::set-output name=is_high_severity::true"
                break
              fi
            done
          fi
      - name: Block merge if high severity
        if: steps.dependabot_check.outputs.is_high_severity == 'true'
        run: |
          echo "::error title=Blocking Pull Request::This pull request cannot be merged automatically due to its critical or high severity."
          exit 1
