name: Dependabot Security Updates

on:
  pull_request:
    branches: [main]  # Hangi branchlerde çalışacağını belirtin

jobs:
  security-updates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Dependabot
        uses: dependabot/fetch-metadata@v1
        with:
          primary: security
      - name: Check for security vulnerabilities
        if: steps.dependabot.outputs.alerts > 0
        run: |
          for alert in ${{ steps.dependabot.outputs.alerts }}; do
            if contains("${{ alert.title }}", "critical") || contains("${{ alert.title }}", "high"); then
              echo "::error title=Security Vulnerability Found::A critical or high severity vulnerability has been found. Please address this issue before merging."
              exit 1
            fi
          done
