name: 'Dependabot Critical/High Alert Check'
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  dependabot-critical-high-check:
    name: 'Critical/High Alert Check'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3

      - name: 'Fetch Dependabot Alerts'
        id: fetch-alerts
        uses: actions/github-script@v6
        with:
          script: |
            const query = `
              query {
                repository(owner: "${context.repo.owner}", name: "${context.repo.repo}") {
                  vulnerabilityAlerts(first: 100, states: OPEN) {
                    nodes {
                      securityAdvisory {
                        severity
                        summary
                      }
                      vulnerableManifestPath
                      vulnerableRequirements
                    }
                  }
                }
              }
            `;
            const result = await github.graphql(query);
            console.log("GraphQL Query Result:", JSON.stringify(result, null, 2));  // Debug için
            const alerts = result.repository.vulnerabilityAlerts.nodes.filter(alert => 
              alert.securityAdvisory.severity === 'CRITICAL' || alert.securityAdvisory.severity === 'HIGH'
            );
            console.log("Filtered Alerts:", JSON.stringify(alerts, null, 2));  // Debug için
            return alerts;

      - name: 'Fail if Critical/High Alerts Exist'
        if: steps.fetch-alerts.outputs.result.length > 0
        run: |
          echo "Critical or High severity Dependabot alerts detected!"
          echo "Number of alerts: ${{ steps.fetch-alerts.outputs.result.length }}"
          exit 1
