name: 'Dependabot Critical/High Alert Check'
on:
  push:
    branches:
      - master  # İstediğiniz branch'leri buraya ekleyin
  pull_request:
    branches:
      - master  # PR'lar için kontrol edilecek branch'ler

jobs:
  dependabot-critical-high-check:
    name: 'Critical/High Alert Check'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3

      - name: 'Fetch Dependabot Alerts'
        id: fetch-alerts
        uses: actions/github-script@v6
        with:
          script: |
            const { data: alerts } = await github.rest.dependabot.listAlertsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
             
