name: 'Dependabot Critical/High Alert Check'
on:
  push:
    branches:
      - master  # master branch'i için push olayı
  pull_request:
    branches:
      - master  # master branch'i için PR olayı

jobs:
  dependabot-critical-high-check:
    name: 'Critical/High Alert Check'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3

      - name: 'Fetch Dependabot Alerts'
        id: fetch-alerts
        uses: actions/github-script@v6
        with:
          script: |
            const { data: alerts } = await github.rest.codeScanning.listAlertsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              severity: 'critical,high'  // Yalnızca critical ve high uyarıları çek
            });
            return alerts;  // alerts dizisini döndür

      - name: 'Fail if Critical/High Alerts Exist'
        if: steps.fetch-alerts.outputs.result.length > 0
        run: |
          echo "Critical or High severity Dependabot alerts detected!"
          echo "Number of alerts: ${{ steps.fetch-alerts.outputs.result.length }}"
          exit 1
